name: publish

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  build-win:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: cargo test --verbose

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-mingw-w64-x86-64 gcc-mingw-w64-i686
          rustup target add x86_64-pc-windows-gnu

          mkdir dist
          mkdir builds

      - name: Cached dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build Win64
        run: |
          cargo rustc --bin tainer-cli --release --target=x86_64-pc-windows-gnu -- -C linker=x86_64-w64-mingw32-gcc
          mkdir builds/tainer-cli-win64
          cp target/x86_64-pc-windows-gnu/release/tainer-cli.exe builds/tainer-cli-win64
          7z a dist/tainer-cli-win64.zip ./builds/tainer-cli-win64

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            dist/tainer-cli-win64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
